### ISSUE TITLE
how to save the set properties ?

### ISSUE THREAD

**Issue by liufsd** [steveukx/properties#13]

**Comment by steveukx** [comment]
Flattening the properties back into a properties file can be done a number of ways, probably easiest by using the `.each` function to iterate over the properties currently in the object.

```
const fs = require('fs');
const reader = require('properties-reader')('props.properties');

let saved = [];
properties.each((key, val) => saved.push(`${key} = ${val}`);

fs.writeFile(
  'props.properties', saved.join('\n'), (err) => {
    if (err) throw err;
    console.log('It\'s saved!');
  });
```

There would currently be no way of restoring the use of `[section]` groupings though as these are discarded once the properties file has been read, nor would it be possible to restore file separation when the properties reader has been used to merge together properties from multiple files.
