### ISSUE TITLE
Cannot read URLs

### ISSUE THREAD

**Issue by zobarov** [steveukx/properties#17]
Define URL in properties:
[trade]
base.api.url=http://google.com

Call:
const baseApiUrl = generalProperties.read('trade.base.api.url');

Result:
"[object Object]/public/getmarkets"

It's ok if you change the value to something plain

**Comment by steveukx** [comment]
It looks like you're using the `.read` function to retrieve values, but this is used to read the supplied string into the `propertiesReader`.

You should find that switching to `.get` makes this work:

```
const propertiesReader = require('properties-reader');
const generalProperties = propertiesReader();
generalProperties.read(`
[trade]
base.api.url=http://google.com
`);

const baseApiUrl = generalProperties.get('trade.base.api.url'); // will be http://google.com
```

If your properties are in a properties file, you can remove the `.read` block by just passing the path to the file when the reader is created:

```
const propertiesReader = require('properties-reader');
const propertiesFile = `${ __dirname }/general.properties`;

const generalProperties = propertiesReader(propertiesFile);
const baseApiUrl = generalProperties.get('trade.base.api.url'); // will be http://google.com
```

**Comment by zobarov** [comment]
Yes, I can confirm it's ok with get(). Just now so obvious from documentation.
Thank you for quick turnaround!
