### ISSUE TITLE
How to read other format nls files?

### ISSUE THREAD

**Issue by ShrekHuo** [steveukx/properties#31]
How to read other format nls files? Like test.js, in the test.js, there are some key and value like below format:
({
key1: "value1",
key2: "value2",
})
Thanks.

**Comment by steveukx** [comment]
Hi, this library is only really aimed at parsing `.ini` / `.properties` formatted files. For a JSON structure (as in your question), you should be able to either `require('./test')` the file directly or pass the content through `JSON.parse(FS.readFileSync('./test.json', 'utf8'))`.
