### ISSUE TITLE
Not exactly an issue, but some further explainations maybe ?

### ISSUE THREAD

**Issue by M4shy** [steveukx/properties#33]
From the main explanation, it says that properties contents can be displayed either by 'getAllProperties' or by looping through them with the .each((key, value) => {}) iterator. Sorry for my weak 'culture', but it would be nice if you can provide an example in this the case either with the iterator. Thanks in adance, good job!

**Comment by steveukx** [comment]
Hi, I've added a note to the readme for you... `reader.each` is a function that you pass a function to which will be called for each item in the properties, used as `reader.each((key, value) => { /* use the properties here */ })`
