### ISSUE TITLE
Does not consider the case of properties whose parents are also properties

### ISSUE THREAD

**Issue by joe-adams** [steveukx/properties#9]
I don't think my title was very good but this is what I mean.

Consider this property file:

app=My App
app.version=2

First this library will create a property called this._propertiesExpanded.app and set it equal to 'My App'.  Then it will try to create this._propertiesExpanded.app.version.  This will fail because this._propertiesExpanded.app is a string, not an object and it can't have properties.

I could fix it, at least for my own purposes, but I'm a bit confused by the line in the set method:
source = (source[step] = source[step] || {});

What exactly does that do?  It seems to be doing a few things at once on that line.

**Comment by shanimal** [comment]
I have the same problem with one of our legacy .properties i18n files. I just want to point out that fixing this issue (assign keys to a String) it might cause issues for people who are using this to convert the object to JSON.

**Comment by steveukx** [comment]
My current plan is to interpret the object for `.path()` at the time it is requested rather than as the properties object is built, deferring this `TypeError` out of construction.

Adding an option to ignore the property tree of primitives would probably resolve this case - 

````
properties = {};
properties.a = new String('a');
properties.a.b = 'b';

JSON.stringify(properties); // {"a": "a"}
properties.a.b === 'b'; // true
````

**Comment by shanimal** [comment]
Also, two problems exist. The first is when we try to assign an object to a string (which throws an error) the other is when the object already exists an we try to assign a string to it.

**Comment by RichardSimko** [comment]
What's the ETA on this? I'm working on a fix but I'm afraid it won't quite be up to the standard of making a PR.

**Comment by steveukx** [comment]
Apologies about the delay, I've had a lot of other things on - festive break seems like as good a time as any to work on this.

**Comment by RichardSimko** [comment]
No worries, I'll keep tuned :)

**Comment by RichardSimko** [comment]
What would be a reasonable default when trying to get this property? I.e. what should properties.get('app') give in the original example? The string "My app" or the object containing all values below?

I feel like the first one makes more sense but they both have their uses.

**Comment by steveukx** [comment]
I am of the opinion that overwriting the original string value with an object should mean that the original string is replaced so the returned value would be the object.

**Comment by RichardSimko** [comment]
That does make sense. The way get is implemented currently it primarily looks in the _properties object which means that 'app' will resolve to "My app" in the example.

I have implemented what seems to be a functioning solution in terms of the parsing at least, I'll make a PR so you can have a look at it if you like. If you have any ideas about how to modify the getter then I'd love to hear them!
